# core/migrations/__init__.py

"""
This is the migrations directory for the core application.

Django uses this directory to store migration files that are generated 
when changes are made to the models in the core app. Migrations are 
used to apply these changes to the database schema.

Migration files should not be manually edited. They are automatically 
generated by Django's `makemigrations` command and applied using the 
`migrate` command.

Modules:
    - This module does not contain any specific code and serves to mark 
      this directory as a Python package.
"""

# You can add initialization code here if needed, but usually, this file
# remains empty.
